"""empty message

Revision ID: 310359c98386
Revises: 3123f4fa9062
Create Date: 2020-03-27 09:26:04.223113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '310359c98386'
down_revision = '3123f4fa9062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WeConnectPosts',
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('emailId', sa.String(length=250), nullable=True),
    sa.Column('text', sa.String(length=999999), nullable=True),
    sa.Column('images', sa.String(length=999999), nullable=False),
    sa.PrimaryKeyConstraint('postId', 'images')
    )
    op.create_table('WeConnectUsers',
    sa.Column('emailId', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('sex', sa.String(length=250), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('emailId')
    )
    op.drop_table('WeConnect_Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WeConnect_Users',
    sa.Column('emailId', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('isVerified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('emailId', name='WeConnect_Users_pkey')
    )
    op.drop_table('WeConnectUsers')
    op.drop_table('WeConnectPosts')
    # ### end Alembic commands ###
