"""empty message

Revision ID: 3123f4fa9062
Revises: 
Create Date: 2020-03-25 13:10:00.222442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3123f4fa9062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WeConnect_Users',
    sa.Column('emailId', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('sex', sa.String(length=250), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('emailId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WeConnect_Users')
    # ### end Alembic commands ###
