"""empty message

Revision ID: f3353f7c5e90
Revises: 
Create Date: 2020-03-25 12:01:45.168880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3353f7c5e90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WeConnect_Users', sa.Column('isVerified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WeConnect_Users', 'isVerified')
    # ### end Alembic commands ###
