"""empty message

Revision ID: dff0d12f564f
Revises: 874b742c2e9d
Create Date: 2020-03-23 20:45:38.785734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff0d12f564f'
down_revision = '874b742c2e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WeConnect_Users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('WeConnect_Users', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('WeConnect_Users', 'sex',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WeConnect_Users', 'sex',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('WeConnect_Users', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('WeConnect_Users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
